language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: N/SkYR5Bzr0p4n/imtcC90/fWMp2/3bUm+CqNe87Y+QGxdK23779yG73onxdJJ1rf8tzuJxxIXN3R1ad2v5HRLKdTHCH1VTN8OCoOXtDfEyebBbaPHUKwOV2f7SkOGAeSCnHVBTAmti8G38j5DfJmbh+X63RWYrv7Pzq53UFJbp4wI6LqlOhooRmy+/5jGkksO8+pSEAOvBuZg4ZAtWEVDgnsT9LsLgjKhM+A1fRXTokCnzdNa84TIpWLo/1LHe1gI2SFDV7hGwqBPNumLxBkgkDHCBQIlkzBXvTvrJRTusj/IoeC9l/+mtwazrIeYKfW2d54MdwZaWRAGNgorN2UADnsopwwjP48FrZt2/2BrCc8DZLqGIbb8NBiV1oLfOBspqJOV3qTjLmn+nFYZO7gf5QLbTDsOOfslUBi2awE2OpOdH/S033mD7VDmoEen7GOkRQEjakNzJ3Sro9V4jvWM8d3IIrACKUXQEAkyarumwJcJzLfGXtcXKXyWGUcBeE7VPJTlO8/z+8BPG8iSWTpOskh3XE08IcGVqn1/zSCHsHeE4BikTSxmsQttQvtINOGPTSZlq1xZvNUTWZcCPwetViMUPAyLNPObrCtNlBtKvj7PanBvt2KAD84LR2iVol8XDQ0FmV+H0CZuIdNuo5b2SVfygoJdtVxqUCxOWdCpI=
  app: salty-spire-25674
  on:
    repo: OtakuToronto/Sample-Travis-Heroku
